services:
- { 
    name_service: "web-server", 
    image: "nginx:1.13",
    port: 80,
    publish_port: 8080,
    net_mode: "ingress",
    mount_dst: "/tmp/",
    mount_src: "/home/natannegara",
    mount_type: bind,
    replica: 2
  }

- { 
    name_service: "mongo-db", 
    image: "mongo:4-xenial",
    port: 27017,
    publish_port: 27017,
    net_mode: "ingress",
    mount_dst: "/data/db",
    mount_src: "mongo_data",
    mount_type: volume,
    replica: 1
  }

volumes:
- {
    name: mongo_data,
    backup: {
      # turn True when you need to backup the volume in case there is migration
      create_backup: True,
      dest: "/home/natannegara"
    }
  }

delete_services: 
  - "web-server-two"

delete_volumes: 
  - "mydata"
