services:
- { 
    name_service: "web-server-test",  
    image: "nginx:1.13",
    port: 80,
    publish_port: 8090,
    net_mode: "ingress",
    mount_dst: "/tmp/",
    mount_src: "/home/natannegara",
    mount_type: bind,
    replica: 3
  }

- { 
    name_service: "mongo-database", 
    image: "mongo:4-xenial",
    port: 27017,
    publish_port: 27018, 
    net_mode: "ingress",
    mount_dst: "/data/db",
    mount_src: "mymongo_data", 
    mount_type: volume,
    replica: 1
  }

volumes:
- {
    name: mymongo_data, 
    backup: {
      # turn True when you need to backup the volume in case there is migration
      create_backup: False,
      dest: "/home/natannegara"
    }
  }

delete_services: 
  - "web-server-two" 

delete_volumes: 
  - "mydata" 
