services:
- { 
    name_service: "web-server",  
    image: "nginx:1.13",
    port: 80,
    publish_port: 8080,
    net_mode: "ingress",
    mount_dst: "/tmp/",
    mount_src: "/home/natannegara",
    mount_type: bind,
    replica: 2
  }

- { 
    name_service: "mongodb-service", 
    image: "mongo:4-xenial",
    port: 27017,
    publish_port: 27018, 
    net_mode: "ingress",
    mount_dst: "/data/db",
    mount_src: "mongodb_data", # this is volume name, we stored data in this volume
    mount_type: volume,
    replica: 1
  }

volumes:
- {
    name: mongodb_data, #init the volume name here
    backup: {
      # turn True when you need to backup the volume in case there is migration
      create_backup: True,
      dest: "/home/natannegara" 
    }
  }

delete_services: 
  - "default" 

delete_volumes: 
  - "default" 
