---

- name: install prerequisites
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: add apt-key
  become: yes
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repo
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: install docker
  become: yes
  apt:
    name: 
      - docker-ce 
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: add user permission
  become: yes
  shell: "usermod -aG docker {{ user }}"

- name: install python package manager
  become: yes
  apt:
    name: python3-pip 

- name: install python sdk
  become_user: "{{ user }}"
  pip:
    name:
      - docker
      - docker-compose