name: Container Description

on: 
  workflow_dispatch:

jobs:
  running-ansible-script-dockerlog:
    runs-on: local-master

    steps:
      - uses: actions/checkout@v3

      - name: Checking Description
        run: |
          ansible-playbook docker-log.yaml
