name: Docker Swarm Preparation

on: 
  workflow_dispatch:

jobs:
  running-ansible-script-dockerprep:
    runs-on: local-master

    steps:
      - uses: actions/checkout@v3

      - name: Install All Dependencies
        run: |
          ansible-playbook docker-prep.yaml
# this script is used for preparation (install docker etc, all dependencies)
